#!/bin/bash

echo "*********************************************************"
echo "Running git pre-commit hook. "
echo "*********************************************************"

export BUILD_SEGMENT_API_KEY=0
endStatus=0

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# check if everything compiles
./gradlew --quiet compileKotlin compileTestKotlin

status=$?
((endStatus+=status))

if [ "$status" = 0 ] ; then
    echo "🟢 Project compiled successfully."
else
    echo 1>&2 "🔴 Project could not be compiled."
fi

# run ktlint apply
./gradlew --quiet ktlintFormat

status=$?
((endStatus+=status))

if [ "$status" = 0 ] ; then
    echo "🟢 KtLint found no issues."
    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add "$file"
      fi
    done
else
    echo 1>&2 "🔴 KtLint found violations it could not fix."
fi

exit $endStatus
